from django.urls import path
from .views import *
from .import views
app_name = 'uniapp'

urlpatterns = [
#Admin Ulrs
    path('', Admin_Dashboard.as_view(), name='admin_dashboard'),
    path('adminAllocatedSubjectsList/<int:semester_id>/', AdminAllocatedSubjectsListView.as_view(), name='adminAllocatedSubjectsList'),
    path('adminSubjectCreate/<int:department_id>/', AdminSubjectCreateView.as_view(), name='adminSubjectCreate'),
    path('adminSubjectList/<int:department_id>/', AdminSubjectListView.as_view(), name='adminSubjectList'),
    path('adminteacherlist/<int:department_id>/', AdminTeacherListView.as_view(), name='adminteacherlist'),
    #Department
    path('departments', DepartmentsView.as_view(), name='departments'),
    path('departmentAdd', DepartmentsAddView.as_view(), name='departmentAdd'),
    path('departmentUpdate/<int:pk>/', DepartmentsUpdateView.as_view(), name='departmentUpdate'),
    path('departmentDelete/<int:pk>/', DepartmentsDeleteView.as_view(), name='departmentDelete'),
    #Semester
    path('semesterlist/<int:department_id>/', SemestersView.as_view(), name='semesterlist'),
    path('semesterAdd/<int:department_id>/', SemesterAddView.as_view(), name='semesterAdd'),
    path('admingraduatestudentslist/<int:department_id>/', AdminGraduateStudentsList.as_view(), name='admingraduatestudentslist'),

#HOD URls
    path('Profile', Profile.as_view(), name='profile'),
    path('ProfilePicChange/<int:pk>/', ProfilePicChangeView.as_view(), name='ProfilePicChange'),
    path('teacher_admin_dashboard', Teacher_Admin_Dashboard.as_view(), name='teacher_admin_dashboard'),
    path('student_dashboard', Student_Dashboard.as_view(), name='student_dashboard'),
    
    path('teacher', TeacherAsUserView.as_view(), name='teacher'),
    path('teacherAllocatedSubjectList', TeacherAllocatedSubjectListView.as_view(), name='teacherAllocatedSubjectList'),
    path('teacherlist', TeacherListView.as_view(), name='teacherlist'),
    path('teacherdelete/<int:pk>/', TeacherDeleteView.as_view(), name='teacherdelete'),
    path('teacherdetail/<int:pk>/', TeacherDetailView.as_view(), name='teacherdetail'),
    path('studentdetail/<int:pk>/', StudentDetailView.as_view(), name='studentdetail'),
    path('subjectlist', SubjectListView.as_view(), name='subjectlist'),
    path('subjectallocation', SubjectAllocationCreateView.as_view(), name='subjectallocation'),
    path('subjectallocationdelete/<int:pk>/', SubjectAllocationDeleteView.as_view(), name='subjectallocationdelete'),
    path('subjectallocationupdate/<int:pk>/', SubjectAllocationUpdateView.as_view(), name='subjectallocationupdate'),
    path('subjectallocationlist', SubjectAllocationListView.as_view(), name='subjectallocationlist'),
    path('subjectcreate', SubjectCreateView.as_view(), name='subjectcreate'),
    path('subjectupdate/<int:pk>/', SubjectUpdateView.as_view(), name='subjectupdate'),
    path('subjectdelete/<int:pk>/', SubjectDeleteView.as_view(), name='subjectdelete'),
    path('semester', SemesterListView.as_view(), name='semester'),
    path('semester/<int:semester_id>/students', StudentListWithSemesterView.as_view(), name='studentlist'),
    path('update_semester/', UpdateSemesterView.as_view(), name='update-semester'),
    path('semester/<int:semester_id>/subject/<int:subjectallocationmodel_id>/', StudentListWithSemesterView.as_view(), name='studentlistattendence'),
    path('studentdelete/<int:pk>/', StudentDeleteView.as_view(), name='studentdelete'),
    path('allstudentlist', AllStudentListView.as_view(), name='allstudentlist'),
    path('adminallstudentlist/<int:department_id>/', AdminAllStudentListView.as_view(), name='adminallstudentlist'),
    path('graduatestudentslist', GraduateStudentsList.as_view(), name='graduatestudentslist'),
    path('studentcreate', StudentCreateView.as_view(), name='studentcreate'),
    path('studentupdate/<int:pk>/', StudentUpdateView.as_view(), name='studentupdate'),
    path('ajax_load_provinces', views.load_province, name='ajax_load_provinces'),
    path('ajax_load_districts', views.load_district, name='ajax_load_districts'),
    path('ajax_load_semesters', views.load_semesters, name='ajax_load_semesters'),
    path('semester/<int:semester_id>/create', StudentCreateSemesterView.as_view(), name='studentcreatesemester'),
    path('attendence/<int:semester_id>/subject/<int:subjectallocationmodel_id>/', views.MarkAttendanceView, name='attendence'),
    path('attendenceview', AttendenceSubjectView.as_view(), name='attendenceview'),
    path('semesterattendenceview/<int:semester_id>/', AttendenceSubjectView.as_view(), name='semesterattendenceview'),
    path('attendenceviewForTeacher/<int:semester_id>/', AttendenceSubjectView.as_view(), name='attendenceviewForTeacher'),
    path('attendencedate/<int:subjectallocationmodel_id>/', AttendenceDateView.as_view(), name='attendencedate'),
    path('attendencedetail/<int:attendence_id>', AttendenceDetailView.as_view(), name='attendencedetail'),
    path('attendenceupdate/<int:pk>/', AttendenceUpdateView.as_view(), name='attendenceupdate'),
    path('attendenceDateUpdate/<int:pk>/', AttendenceDateUpdateView.as_view(), name='attendenceDateUpdate'),
    path('attendenceDelete/<int:pk>/', AttendenceDetailDeleteView.as_view(), name='attendenceDelete'),
    path('attendenceDateDelete/<int:pk>/', AttendenceDateDeleteView.as_view(), name='attendenceDateDelete'),
    path('subject/<int:subjectallocationmodel_id>/student/<int:student_id>/attendence', StudentAttendenceDateView.as_view(), name='studentattendencedate'),
    path('assessment/<int:subjectallocationmodel_id>/', Assessment.as_view(), name='assessment'),
    path('AssessmentSubject/<int:student_id>/', AssessmentSubjectView.as_view(), name='AssessmentSubject'),
    path('update_session', views.update_session, name='update_session'),
    path('assignmentAdd/<int:subjectallocationmodel_id>/', AssignmentAddView.as_view(), name='assignmentAdd'),
    path('assignmentUpdate/<int:pk>/', AssignmentUpdateView.as_view(), name='assignmentUpdate'),
    path('assignmentDelete/<int:pk>/', AssignmentDeleteView.as_view(), name='assignmentDelete'),
    path('assignmentView/<int:subjectallocationmodel_id>/', AssignmentView.as_view(), name='assignmentView'),
    path('quizAdd/<int:subjectallocationmodel_id>/', QuizAddView.as_view(), name='quizAdd'),
    path('quizUpdate/<int:pk>/', QuizUpdateView.as_view(), name='quizUpdate'),
    path('quizDelete/<int:pk>/', QuizDeleteView.as_view(), name='quizDelete'),
    path('quizView/<int:subjectallocationmodel_id>/', QuizView.as_view(), name='quizView'),
    path('presentationAdd/<int:subjectallocationmodel_id>/', PresentationAddView.as_view(), name='presentationAdd'),
    path('presentationUpdate/<int:pk>/', PresentationUpdateView.as_view(), name='presentationUpdate'),
    path('presentationDelete/<int:pk>/', PresentationDeleteView.as_view(), name='presentationDelete'),
    path('presentationView/<int:subjectallocationmodel_id>/', PresentationView.as_view(), name='presentationView'),
    path('midAdd/<int:subjectallocationmodel_id>/', MidAddView.as_view(), name='midAdd'),
    path('midUpdate/<int:pk>/', MidUpdateView.as_view(), name='midUpdate'),
    path('midDelete/<int:pk>/', MidDeleteView.as_view(), name='midDelete'),
    path('midView/<int:subjectallocationmodel_id>/', MidView.as_view(), name='midView'),
    path('finalAdd/<int:subjectallocationmodel_id>/', FinalAddView.as_view(), name='finalAdd'),
    path('finalUpdate/<int:pk>/', FinalUpdateView.as_view(), name='finalUpdate'),
    path('finalDelete/<int:pk>/', FinalDeleteView.as_view(), name='finalDelete'),
    path('finalView/<int:subjectallocationmodel_id>/', FinalView.as_view(), name='finalView'),
    path('result/<int:subjectallocationmodel_id>/', SubjectTotalMarksView.as_view(), name='result'),
    path('allSubjectsMarks', AllSubjectsMarksView.as_view(), name='allSubjectsMarks'),
    # path('show_date_form', AllSubjectsMarksView.as_view(), name='show_date_form'),
    path('SubjectsForThatSemester/<int:semester_id>/', SubjectsForThatSemester.as_view(), name='SubjectsForThatSemester'),
    #Student As User Urls
    path('Student_Attendance_Subjects', StudentAttendanceSubjectsView.as_view(), name='Student_Attendance_Subjects'),
    path('Student_Attendance/<int:subject_id>/', StudentAttendanceView.as_view(), name='Student_Attendance'),
    path('student_result_view', StudentResultView.as_view(), name='student_result_view'),
    path('marks_subject/<int:semester_id>/', StudentMarksSubjects.as_view(), name='marks_subject'),
    path('student_paper_marks/<int:subject_id>/', StudentPaperMarks.as_view(), name='student_paper_marks'),
    path('adminsubjectallocation', AdminSubjectAllocationCreateView.as_view(), name='adminsubjectallocation'),
]